"""
C++ related search terms for YouTube video collection
"""

# Comprehensive list of C++ related search terms
SEARCH_TERMS = [
    # General C++ Programming
    "C++ programming",
    "C++ tutorial",
    "C++ tutorial for beginners",
    "C++ advanced",
    "C++ course",
    "C++ programming language",
    # C++ Standards
    "C++11",
    "C++14",
    "C++17",
    "C++20",
    "C++23",
    "modern C++",
    "C++ standard",
    # C++ Core Concepts
    "C++ pointers",
    "C++ references",
    "C++ memory management",
    "C++ smart pointers",
    "C++ RAII",
    "C++ templates",
    "C++ template metaprogramming",
    "C++ lambda",
    "C++ lambda expressions",
    "C++ STL",
    "C++ standard library",
    "C++ containers",
    "C++ iterators",
    "C++ algorithms",
    # C++ Features
    "C++ classes",
    "C++ inheritance",
    "C++ polymorphism",
    "C++ virtual functions",
    "C++ operator overloading",
    "C++ exceptions",
    "C++ move semantics",
    "C++ rvalue references",
    "C++ constexpr",
    "C++ const",
    "C++ const correctness",
    # C++ Advanced Topics
    "C++ concurrency",
    "C++ multithreading",
    "C++ threads",
    "C++ async",
    "C++ futures",
    "C++ promises",
    "C++ mutex",
    "C++ lock",
    "C++ atomic",
    "C++ memory model",
    # C++ Data Structures & Algorithms
    "C++ data structures",
    "C++ algorithms",
    "C++ sorting",
    "C++ binary search",
    "C++ graph algorithms",
    "C++ tree",
    "C++ hash table",
    "C++ map",
    "C++ vector",
    "C++ list",
    "C++ deque",
    "C++ set",
    "C++ unordered_map",
    # C++ Design & Best Practices
    "C++ design patterns",
    "C++ SOLID principles",
    "C++ best practices",
    "C++ code review",
    "C++ clean code",
    "C++ refactoring",
    "C++ testing",
    "C++ unit testing",
    "C++ TDD",
    # C++ Performance
    "C++ performance",
    "C++ optimization",
    "C++ profiling",
    "C++ benchmarking",
    "C++ cache optimization",
    "C++ compiler optimization",
    # C++ Libraries & Frameworks
    "Boost C++",
    "Qt C++",
    "C++ OpenCV",
    "C++ SFML",
    "C++ SDL",
    "C++ Eigen",
    "C++ spdlog",
    "C++ fmt",
    "C++ catch2",
    "C++ gtest",
    # C++ Application Domains
    "C++ game development",
    "C++ game engine",
    "C++ graphics programming",
    "C++ embedded",
    "C++ embedded systems",
    "C++ systems programming",
    "C++ network programming",
    "C++ socket programming",
    "C++ database",
    "C++ web development",
    "C++ backend",
    # C++ Tools & Environment
    "C++ CMake",
    "C++ Makefile",
    "C++ gcc",
    "C++ clang",
    "C++ MSVC",
    "C++ Visual Studio",
    "C++ CLion",
    "C++ VS Code",
    "C++ debugger",
    "C++ gdb",
    "C++ valgrind",
    "C++ sanitizers",
    # C++ Learning & Career
    "C++ interview",
    "C++ interview questions",
    "C++ coding interview",
    "C++ LeetCode",
    "C++ competitive programming",
    "C++ programming challenges",
    "C++ projects",
    "C++ portfolio",
    # Specific Topics
    "C++ RAII",
    "C++ copy constructor",
    "C++ move constructor",
    "C++ destructor",
    "C++ friend",
    "C++ namespace",
    "C++ enum",
    "C++ union",
    "C++ struct",
    "C++ typedef",
    "C++ using",
    "C++ auto",
    "C++ decltype",
    "C++ typeid",
    "C++ RTTI",
    "C++ CRTP",
    "C++ SFINAE",
    "C++ concepts",
    "C++ modules",
    "C++ coroutines",
    "C++ ranges",
    "C++ span",
    "C++ string_view",
    "C++ optional",
    "C++ variant",
    "C++ any",
    "C++ filesystem",
    "C++ chrono",
    "C++ regex",
    "C++ random",
    "C++ iostream",
    "C++ fstream",
    "C++ string",
    "C++ array",
    "C++ tuple",
    "C++ pair",
]

# Channel-specific searches (if you want to focus on specific channels)
C_PLUS_PLUS_CHANNELS = [
    "Meeting C++",
    "CppCon",
    "TheCherno",
    "Jason Turner",
    "Bisqwit",
    "Bo Qian",
    "freeCodeCamp.org C++",
    "Programming with Mosh C++",
]

# Individual C++ Creators/Experts
C_PLUS_PLUS_CREATORS = [
    "Bjarne Stroustrup",
    "Jason Turner",
    "Herb Sutter",
    "Nicolai Josuttis",
    "Chandler Carruth",
    "Kate Gregory",
]

# Playlist searches
C_PLUS_PLUS_PLAYLISTS = [
    "C++ tutorial playlist",
    "C++ complete course",
    "C++ from scratch",
    "C++ advanced topics",
    "C++ STL tutorial",
]
